# Generated by Django 5.0.1 on 2024-01-03 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voter",
            old_name="mother_maiden_last_name",
            new_name="mother_maiden_middle_name",
        ),
    ]
